name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working_directory: ./advent

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{env.working_directory}}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{env.working_directory}}
